receivers:
  otlp:
    protocols:
      grpc:

processors:
  resource:
    attributes:
      - key: environment
        action: insert
        value: ${env:ENVIRONMENT}
  memory_limiter:
    check_interval: 1s
    limit_mib: 800
  batch:

exporters:
  logging:
    verbosity: detailed
  otlp/elastic:
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: ${env:ELASTIC_APM_SERVER_ENDPOINT}
    headers:
      # Elastic APM Server secret token with the format "Bearer <apm_secret_token>"
      Authorization: ${env:ELASTIC_APM_SECRET_TOKEN}

extensions:
  health_check:
    path: "/health-check"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ logging, otlp/elastic ]
    metrics:
      receivers: [ otlp ]
      exporters: [ logging, otlp/elastic ]
    logs:
      receivers: [ otlp ]
      exporters: [ logging, otlp/elastic ]