name: DEPLOYMENT

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out caller repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Checking out reusable workflow repository
        uses: actions/checkout@v3
        with:
          repository: rewardsweb/rewardsweb-iac-scripts-project
          token:      ${{ secrets.PERSONAL_TOKEN }}
          path:       rewardsweb/rewardsweb-iac-scripts-project

      - name: Configure Java and Gradle
        uses: "${{ vars.path }}/.github/actions/configure-java-gradle"
