name: DEPLOYMENT

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out caller repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get penultimate tag
        id: penultimate-tag
        run: echo "tag-name=$(git describe --abbrev=0 --match="docker-image-v*" --tags HEAD~)" >> $GITHUB_OUTPUT
      
      - name: echo penultimate 
        run: echo ${{ steps.penultimate-tag.outputs.tag-name }}
